# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY ./api/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of your application code
COPY ./api ./

# Build the TypeScript code
RUN npm run build

# Expose the port the app runs on
EXPOSE 5000

# Command to run your app (start after build)
CMD ["npm", "start"]