services:
  postgres:
    image: postgres
    container_name: hias-db
    environment:
      POSTGRES_USER: hias-user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hias
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: hias-api
    environment:
      POSTGRES_USER: hias-user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hias
      POSTGRES_HOST: postgres
      NODE_ENV: production
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    command: ["npm", "run", "start"]