name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint-and-test-backend:
    name: Lint and Test Backend
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./api

      # Step 4: Build the backend if necessary (you can remove this if not needed)
      - name: Build Backend
        run: npm run build
        working-directory: ./api